
all:
	cc -g problem-1.c linked_list.c linked_list.h -o problem-1
	cc -g problem-2.c linked_list.c linked_list.h -o problem-2
	cc -g problem-2.c linked_list.c linked_list.h -o problem-3
	cc -g problem-4.c linked_list.c linked_list.h -o problem-4


clean:
	rm -fr problem-1 problem-2 problem-3 problem-4
