
all:
	@echo "Building all ...\n"
	cc -g problem-1.c linked_list.c linked_list.h -o problem-1
	cc -g problem-2.c linked_list.c linked_list.h -o problem-2
	cc -g problem-3.c linked_list.c linked_list.h -o problem-3
	cc -g problem-4.c linked_list.c linked_list.h -o problem-4
	cc -g problem-5.c linked_list.c linked_list.h -o problem-5
	cc -g problem-6.c linked_list.c linked_list.h -o problem-6
	cc -g problem-7.c linked_list.c linked_list.h -o problem-7
	cc -g problem-8.c linked_list.c linked_list.h -o problem-8

	@echo "Test all ...\n"
	@echo "======>>\n"
	./problem-1
	@echo "<<======\n"
	@echo "======>>\n"
	./problem-2
	@echo "<<======\n"
	@echo "======>>\n"
	./problem-3
	@echo "<<======\n"
	@echo "======>>\n"
	./problem-4
	@echo "<<======\n"
	@echo "======>>\n"
	./problem-5
	@echo "<<======\n"
	@echo "======>>\n"
	./problem-6
	@echo "<<======\n"
	@echo "======>>\n"
	./problem-7
	@echo "<<======\n"
	@echo "======>>\n"
	./problem-8
	@echo "<<======\n"

clean:
	rm -fr problem-1 problem-2 problem-3 problem-4 problem-5 problem-6 problem-7 problem-8
